# -*- coding: utf-8 -*-
"""main belanja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Efftk-PynBKnqM8qm0jdKTGKX3-pevl1
"""

import transaksi_belanja as tb
import os
from time import sleep

print('-------------------------------------------------')
print('Selamat Datang di Kasir Online PACMANN')
print('-------------------------------------------------')
nama = str(input('Silahkan Masukan Nama Anda : '))

os.system('cls')
print('-------------------------------------------------')
print('Selamat Datang di Kasir Online PACMANN')
print('-------------------------------------------------')
print(f'Selamat Datang {nama}!')
print('\n')
ready = str(input('Apakah kamu sudah siap untuk input belanjaan kamu? (Y / N): ')).lower()
try:
  if ready == 'y':
    os.system('cls')
    nama = tb.Transaction
    nama.menu()
  elif ready == 'n':
    print('-------------------------------------------------')
    print('Silahkan datang kembali ketika sudah siap input belanjaan :)')
    print('Aplikasi akan automatis tertutup dalam 3 detik!')
    sleep(3)
    pass
  else:
    print('-------------------------------------------------')
    print('Input anda salah, silahkan restart program!')
    print('Aplikasi akan automatis tertutup dalam 3 detik!')
    sleep(3)
    pass
except:
  print('-------------------------------------------------')
  print('Input anda salah, silahkan restart program!')
  print('Aplikasi akan automatis tertutup dalam 3 detik!')
  sleep(3)